### ISSUE TITLE
Polymod file system causing compiling ti break

### ISSUE THREAD

**Issue by SpookyMan16** [larsiusprime/polymod#121] opened 2022-05-22 14:53 UTC
Every time I try and compile a haxe project I have the error of:
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/fs/PolymodFileSystem.hx:19: characters 16-18 : Expected )

Edit: I used non git and now I have new errors
New errors:

C:/HaxeToolkit/haxe/lib/polymod/1,5,3/polymod/hscript/PolymodScriptClass.hx:71: characters 52-56 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/1,5,3/polymod/hscript/PolymodScriptClass.hx:74: characters 87-91 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/1,5,3/polymod/hscript/PolymodScriptClass.hx:357: characters 17-18 : hscript.Error has no field e
C:/HaxeToolkit/haxe/lib/polymod/1,5,3/polymod/hscript/PolymodScriptClass.hx:373: characters 70-74 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/1,5,3/polymod/hscript/PolymodScriptClass.hx:379: characters 70-74 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/1,5,3/polymod/hscript/PolymodScriptClass.hx:384: characters 70-74 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/1,5,3/polymod/hscript/PolymodScriptClass.hx:388: characters 69-73 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/1,5,3/polymod/hscript/PolymodScriptClass.hx:392: characters 69-73 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/1,5,3/polymod/hscript/PolymodScriptClass.hx:396: characters 69-73 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/1,5,3/polymod/hscript/PolymodInterpEx.hx:134: characters 9-15 : hscript.Interp has no field setVar
C:/HaxeToolkit/haxe/lib/polymod/1,5,3/polymod/hscript/PolymodInterpEx.hx:115: characters 20-26 : Field setVar is declared 'override' but doesn't override any field

**Comment by TorchTheDragon** [comment] 2022-05-31 23:57
I am having the same errors:

C:/Users/[MyPCUsername]/Documents/[MyProject]/%HAXELIB_ROOT%/polymod/git/polymod/hscript/PolymodScriptClass.hx:71: characters 52-56 : hscript.Error has no field line
C:/Users/[MyPCUsername]/Documents/[MyProject]/%HAXELIB_ROOT%/polymod/git/polymod/hscript/PolymodScriptClass.hx:74: characters 87-91 : hscript.Error has no field line
C:/Users/[MyPCUsername]/Documents/[MyProject]/%HAXELIB_ROOT%/polymod/git/polymod/hscript/PolymodScriptClass.hx:357: characters 17-18 : hscript.Error has no field e
C:/Users/[MyPCUsername]/Documents/[MyProject]/%HAXELIB_ROOT%/polymod/git/polymod/hscript/PolymodScriptClass.hx:373: characters 70-74 : hscript.Error has no field line
C:/Users/[MyPCUsername]/Documents/[MyProject]/%HAXELIB_ROOT%/polymod/git/polymod/hscript/PolymodScriptClass.hx:379: characters 70-74 : hscript.Error has no field line
C:/Users/[MyPCUsername]/Documents/[MyProject]/%HAXELIB_ROOT%/polymod/git/polymod/hscript/PolymodScriptClass.hx:384: characters 70-74 : hscript.Error has no field line
C:/Users/[MyPCUsername]/Documents/[MyProject]/%HAXELIB_ROOT%/polymod/git/polymod/hscript/PolymodScriptClass.hx:388: characters 69-73 : hscript.Error has no field line
C:/Users/[MyPCUsername]/Documents/[MyProject]/%HAXELIB_ROOT%/polymod/git/polymod/hscript/PolymodScriptClass.hx:392: characters 69-73 : hscript.Error has no field line
C:/Users/[MyPCUsername]/Documents/[MyProject]/%HAXELIB_ROOT%/polymod/git/polymod/hscript/PolymodScriptClass.hx:396: characters 69-73 : hscript.Error has no field line
C:/Users/[MyPCUsername]/Documents/[MyProject]/%HAXELIB_ROOT%/polymod/git/polymod/hscript/PolymodInterpEx.hx:134: characters 9-15 : hscript.Interp has no field setVar
C:/Users/[MyPCUsername]/Documents/[MyProject]/%HAXELIB_ROOT%/polymod/git/polymod/hscript/PolymodInterpEx.hx:115: characters 20-26 : Field setVar is declared 'override' but doesn't override any field

Yes, I did change my PC username because I don't want anyone knowing my real name, and I also removed my project name, mainly because it was misspelled and I didn't want to get called out for it

**Comment by TorchTheDragon** [comment] 2022-06-01 03:19
@SpookyMan16 I found a temporary solution until this is fixed. Go back to the 1.5.1 version, it seems to work. If you are working on an FNF project, which I am only assuming based off PFP, then here is the direct command to put in there:
`haxelib git polymod https://github.com/larsiusprime/polymod.git v1.5.1`

You do need to delete the old one though because it didn't let me install this one (probably just due to my bad computer) so, you can just use this command:
`haxelib remove polymod`

This is just a temporary solution I found, at least until the newer one gets updated.

**Comment by MasterEric** [comment] 2022-06-02 04:00
Closed as duplicate of #122.

**Closed by MasterEric** 2022-06-02 04:00 UTC
