### ISSUE TITLE
Lime with no frameworkParams causes a crash

### ISSUE THREAD

**Issue by Cheemsandfriends** [larsiusprime/polymod#74] opened 2021-11-23 21:02 UTC
Hello Eric,
I wanted to present the problem before but better do it in the new version right?
I have some problems with this in specific
![imagen](https://user-images.githubusercontent.com/84867412/143122354-fa65bb91-13ae-4c78-ac2e-f55fd85ec733.png)

It gives me a null exception and calls these specific things.
Do you know what may be?
(And sorry for not telling before, I don't use VSCode to compile and the tutorial you gave me was confusing for me 😅)

**Comment by Cheemsandfriends** [comment] 2021-11-23 21:06
Or I think it was what you requested me, If it isn't that then Idk srry

**Comment by Cheemsandfriends** [comment] 2021-11-23 21:10
Nvm

**Comment by Cheemsandfriends** [comment] 2021-11-23 21:11
The problem was the framework Params, but now it works

**Comment by MasterEric** [comment] 2021-11-23 22:11
So @Cheemsandfriends from the error log you gave me it seems like you were missing the framework parameters, which are necessary in Line projects that use multiple asset libraries.

The problem is that there's a null pointer exception being thrown RIGHT before the line that gracefully handed the error and provides you the proper error message, haha:

https://github.com/larsiusprime/polymod/blob/master/polymod/backends/LimeBackend.hx#L130

I'm going to reopen this issue then close it once I make a hotfix.

**Comment by Cheemsandfriends** [comment] 2021-11-24 13:39
Maybe you should trace the errors in Polymod so it isn't so confusing and check if the thing is correct

**Comment by Cheemsandfriends** [comment] 2021-11-24 13:45
Well, At least I helped on something lol

**Comment by MasterEric** [comment] 2021-12-23 21:06
Fixed this.

**Closed by MasterEric** 2021-12-23 21:06 UTC
