### ISSUE TITLE
I got this error when I try to build it for fnf 

### ISSUE THREAD

**Issue by ThatDisabledKid** [larsiusprime/polymod#92] opened 2022-01-19 02:30 UTC
/usr/local/lib/haxe/lib/polymod/git/polymod/backends/FlixelBackend.hx:50: characters 25-30 : openfl.utils.IAssetCache has no field cache

**Comment by MrClogsworthYT** [comment] 2022-01-19 18:32
this isnt the fnf repo

**Comment by MasterEric** [comment] 2022-01-20 01:50
> this isnt the fnf repo

Normally I would agree and close this, but the issue is definitely with this repo. There's a syntax error in the newly released 1.4.0 that prevents compiling.

**Comment by MrClogsworthYT** [comment] 2022-01-20 09:19
> > this isnt the fnf repo
> 
> Normally I would agree and close this, but the issue is definitely with this repo. There's a syntax error in the newly released 1.4.0 that prevents compiling.

then just install an old version of polymod -_-

**Comment by MasterEric** [comment] 2022-01-20 22:33
Version 1.4.1 just got pushed so this should be fixed.

**Closed by MasterEric** 2022-01-20 22:33 UTC
